public_vpc_cidr_block = "10.23.0.0/16"
private_vpc_cidr_block = "10.24.0.0/16"
mc_vpc_cidr_block = "10.0.0.0/16"
public_vpc_name = "byovpcpublic"
private_vpc_name = "byovpcprivate"
k8s_cluster_name = "byovpcprivate"
k8s_management_cluster_name = "golem"